experiment_name: exp_01_roberta_baseline
pipeline: direct

encoder:
  model_name: mental/mental-roberta-base
  num_labels: 5
  max_len: 256
  use_crf: false
  dropout: 0.1

loss:
  type: ce

optimizer:
  base_lr: 2.0e-5
  weight_decay: 0.01
  use_llrd: false

training:
  epochs: 20
  batch_size: 16
  eval_batch_size: 32
  warmup_ratio: 0.1
  grad_clip: 1.0
  seed: 42
  num_workers: 2
  bf16: true

data:
  train_path: datasets/new_train_data.csv
  dev_path:   datasets/new_dev_data.csv

output_dir: out/experiments/exp_01_roberta_baseline
